### ISSUE TITLE
Case Insensitivity

### ISSUE THREAD

**Issue by reedacartwright** [miku/activememory#1]
Currently the test is done in a case-sensitive manner. I recommend that it be case insensitive. This would require using the `.localeCompare()` function.

Thanks for this creating this test.

**Comment by miku** [comment]
Very good point, thanks. I used the "base" sensitivity for now:

> "base": Only strings that differ in base letters compare as unequal. Examples: a ≠ b, a = á, a = A.

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare
