### ISSUE TITLE
words change is very fast

### ISSUE THREAD

**Issue by raynamharris** [miku/activememory#3]
The speed of the quiz is too fast for some learners, especially those who speak English as a second language. can you slow the speed of the tool?

**Comment by miku** [comment]
Thanks for the input, I increased the interval from 600ms to 950ms.

**Comment by raynamharris** [comment]
thanks!

**Comment by miku** [comment]
Additionally, now the delay can be set via URL fragment (in ms), e.g.

* https://miku.github.io/activememory/#delay=300
* https://miku.github.io/activememory/#delay=1000

If nothing is given it defaults to 950ms - as before.

**Comment by raynamharris** [comment]
Nice! I like how there is a default and then you can set the delay at any value! so useful! Thanks!

**Comment by miku** [comment]
Thanks, if you have any more ideas for improvement, please let me know.
