### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by marcodelapierre** [miku/activememory#5]
During the current SWC instructor training session, we were discussing the opportunity of contributing additional languages (I will aim to do that for Italian).

It might be interesting then to provide a URL modifier to select the language.

**Comment by miku** [comment]
Good idea, I just prepared some support for multiple languages - again via a [fragment](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5), example: [https://miku.github.io/activememory/#delay=300,lang=it](https://miku.github.io/activememory/#delay=300,lang=it) - only English and  [Italian](https://github.com/miku/activememory/blob/ad137d1d5130cd81aa4aefbfbce0b7d33bd3d5bc/index.js#L158) so far.

Of course the interface is not translated and overall the page is very bare-bone. 

Please feel free to tweak the word list or any other aspect of the site.

**Comment by marcodelapierre** [comment]
Fantastic, thank you!
Will aim to work on the Italian dictionary as soon as possible.

**Comment by marcodelapierre** [comment]
@avallecam - as we were discussing yesterday during the Carpentries workshop - in case you are interested :-)

**Comment by miku** [comment]
Thanks again!
